
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action AboutAction;
	private global::Gtk.Action GettingStartedAction;
	private global::Gtk.Action LexiconAction;
	private global::Gtk.Action ToolsAction;
	private global::Gtk.Action LongTermGoalsRBMAction;
	private global::Gtk.Action MediumTermGoalsAction;
	private global::Gtk.Action ShortTermGoalsTodayAction;
	private global::Gtk.Action TaskCoachAction;
	private global::Gtk.Action WorkTimerAction;
	private global::Gtk.Action BreakTimerAction;
	private global::Gtk.Action ConfigurationAction;
	private global::Gtk.Action LogicalModellerAction;
	private global::Gtk.VBox vboxMain;
	private global::Gtk.MenuBar menubarMainWindow;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox2;
	private global::Gtk.IconView iconviewProjectWindow;
	private global::Gtk.Label label2;
	private global::Gtk.TextView textviewProjectName;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Label label1;
	private global::Gtk.EventBox eventbox1;
	private global::Gtk.EventBox eventbox7;
	private global::Gtk.ProgressBar progressbarProjectCompletion;
	private global::Gtk.Label GtkLabel3;
	private global::Gtk.Frame frame2;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.VBox vbox4;
	private global::Gtk.EventBox eventbox2;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label label4;
	private global::Gtk.EventBox eventbox4;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label5;
	private global::Gtk.EventBox eventbox5;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label6;
	private global::Gtk.EventBox eventbox6;
	private global::Gtk.Label GtkLabel4;
	private global::Gtk.Statusbar statusbarMainWindow;
	private global::Gtk.Entry entryStatusBarRight;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.GettingStartedAction = new global::Gtk.Action ("GettingStartedAction", global::Mono.Unix.Catalog.GetString ("Getting Started"), null, null);
		this.GettingStartedAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Getting Started");
		w1.Add (this.GettingStartedAction, null);
		this.LexiconAction = new global::Gtk.Action ("LexiconAction", global::Mono.Unix.Catalog.GetString ("Lexicon"), null, null);
		this.LexiconAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Lexicon");
		w1.Add (this.LexiconAction, null);
		this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
		this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
		w1.Add (this.ToolsAction, null);
		this.LongTermGoalsRBMAction = new global::Gtk.Action ("LongTermGoalsRBMAction", global::Mono.Unix.Catalog.GetString ("Long Term Goals (RBM)"), null, null);
		this.LongTermGoalsRBMAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Long Term Goals (RBM)");
		w1.Add (this.LongTermGoalsRBMAction, null);
		this.MediumTermGoalsAction = new global::Gtk.Action ("MediumTermGoalsAction", global::Mono.Unix.Catalog.GetString ("Medium Term Goals"), null, null);
		this.MediumTermGoalsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Medium Term Goals");
		w1.Add (this.MediumTermGoalsAction, null);
		this.ShortTermGoalsTodayAction = new global::Gtk.Action ("ShortTermGoalsTodayAction", global::Mono.Unix.Catalog.GetString ("Short Term Goals (Today)"), null, null);
		this.ShortTermGoalsTodayAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Short Term Goals (Today)");
		w1.Add (this.ShortTermGoalsTodayAction, null);
		this.TaskCoachAction = new global::Gtk.Action ("TaskCoachAction", global::Mono.Unix.Catalog.GetString ("Task Coach"), null, null);
		this.TaskCoachAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Task Coach");
		w1.Add (this.TaskCoachAction, null);
		this.WorkTimerAction = new global::Gtk.Action ("WorkTimerAction", global::Mono.Unix.Catalog.GetString ("Work Timer"), null, null);
		this.WorkTimerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Work Timer");
		w1.Add (this.WorkTimerAction, null);
		this.BreakTimerAction = new global::Gtk.Action ("BreakTimerAction", global::Mono.Unix.Catalog.GetString ("Break Timer"), null, null);
		this.BreakTimerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Break Timer");
		w1.Add (this.BreakTimerAction, null);
		this.ConfigurationAction = new global::Gtk.Action ("ConfigurationAction", global::Mono.Unix.Catalog.GetString ("Configuration"), null, null);
		this.ConfigurationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Configuration");
		w1.Add (this.ConfigurationAction, null);
		this.LogicalModellerAction = new global::Gtk.Action ("LogicalModellerAction", global::Mono.Unix.Catalog.GetString ("Logical Modeller"), null, null);
		this.LogicalModellerAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Logical Modeller");
		w1.Add (this.LogicalModellerAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("workflow  PLANNING STAGE");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vboxMain = new global::Gtk.VBox ();
		this.vboxMain.Name = "vboxMain";
		this.vboxMain.Spacing = 6;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubarMainWindow'><menu name='ToolsAction' action='ToolsAction'><menu name='LongTermGoalsRBMAction' action='LongTermGoalsRBMAction'><menuitem name='LogicalModellerAction' action='LogicalModellerAction'/></menu><menuitem name='MediumTermGoalsAction' action='MediumTermGoalsAction'/><menu name='ShortTermGoalsTodayAction' action='ShortTermGoalsTodayAction'><menuitem name='WorkTimerAction' action='WorkTimerAction'/><menuitem name='BreakTimerAction' action='BreakTimerAction'/></menu><menuitem name='TaskCoachAction' action='TaskCoachAction'/><menuitem name='ConfigurationAction' action='ConfigurationAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/><menuitem name='GettingStartedAction' action='GettingStartedAction'/><menuitem name='LexiconAction' action='LexiconAction'/></menu></menubar></ui>");
		this.menubarMainWindow = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubarMainWindow")));
		this.menubarMainWindow.Name = "menubarMainWindow";
		this.vboxMain.Add (this.menubarMainWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.menubarMainWindow]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.BorderWidth = ((uint)(3));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		this.GtkAlignment.BorderWidth = ((uint)(3));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.iconviewProjectWindow = new global::Gtk.IconView ();
		this.iconviewProjectWindow.CanFocus = true;
		this.iconviewProjectWindow.Name = "iconviewProjectWindow";
		this.hbox2.Add (this.iconviewProjectWindow);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.iconviewProjectWindow]));
		w3.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Project Title:");
		this.hbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.textviewProjectName = new global::Gtk.TextView ();
		this.textviewProjectName.Buffer.Text = "Project Not Loaded,\nplease load or create one.";
		this.textviewProjectName.CanFocus = true;
		this.textviewProjectName.Name = "textviewProjectName";
		this.hbox2.Add (this.textviewProjectName);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.textviewProjectName]));
		w5.Position = 2;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Warnings:");
		this.hbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.eventbox1 = new global::Gtk.EventBox ();
		this.eventbox1.Name = "eventbox1";
		// Container child eventbox1.Gtk.Container+ContainerChild
		this.eventbox7 = new global::Gtk.EventBox ();
		this.eventbox7.Name = "eventbox7";
		this.eventbox1.Add (this.eventbox7);
		this.hbox1.Add (this.eventbox1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.eventbox1]));
		w9.Position = 2;
		this.vbox3.Add (this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.progressbarProjectCompletion = new global::Gtk.ProgressBar ();
		this.progressbarProjectCompletion.Name = "progressbarProjectCompletion";
		this.progressbarProjectCompletion.Text = global::Mono.Unix.Catalog.GetString ("Project Progress To Date:");
		this.vbox3.Add (this.progressbarProjectCompletion);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.progressbarProjectCompletion]));
		w11.Position = 2;
		w11.Expand = false;
		w11.Fill = false;
		this.GtkAlignment.Add (this.vbox3);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel3 = new global::Gtk.Label ();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Project Summary:</b>");
		this.GtkLabel3.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel3;
		this.vbox2.Add (this.frame1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.BorderWidth = ((uint)(1));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		this.GtkAlignment1.BorderWidth = ((uint)(3));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.eventbox2 = new global::Gtk.EventBox ();
		this.eventbox2.Name = "eventbox2";
		// Container child eventbox2.Gtk.Container+ContainerChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Start:");
		this.hbox3.Add (this.label4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label4]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.eventbox4 = new global::Gtk.EventBox ();
		this.eventbox4.Name = "eventbox4";
		this.hbox3.Add (this.eventbox4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.eventbox4]));
		w16.Position = 2;
		this.eventbox2.Add (this.hbox3);
		this.vbox4.Add (this.eventbox2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.eventbox2]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Estimated Completion:");
		this.hbox4.Add (this.label5);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label5]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.eventbox5 = new global::Gtk.EventBox ();
		this.eventbox5.Name = "eventbox5";
		this.hbox4.Add (this.eventbox5);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.eventbox5]));
		w20.Position = 2;
		this.vbox4.Add (this.hbox4);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
		w21.Position = 1;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Last Report Submitted:");
		this.hbox5.Add (this.label6);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label6]));
		w22.Position = 0;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.eventbox6 = new global::Gtk.EventBox ();
		this.eventbox6.Name = "eventbox6";
		this.hbox5.Add (this.eventbox6);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.eventbox6]));
		w23.Position = 2;
		this.vbox4.Add (this.hbox5);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		this.GtkAlignment1.Add (this.vbox4);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel4 = new global::Gtk.Label ();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Signiificant Project Dates:</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel4;
		this.vbox2.Add (this.frame2);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		this.vboxMain.Add (this.vbox2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.vbox2]));
		w28.Position = 1;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.statusbarMainWindow = new global::Gtk.Statusbar ();
		this.statusbarMainWindow.Name = "statusbarMainWindow";
		this.statusbarMainWindow.Spacing = 6;
		// Container child statusbarMainWindow.Gtk.Box+BoxChild
		this.entryStatusBarRight = new global::Gtk.Entry ();
		this.entryStatusBarRight.CanFocus = true;
		this.entryStatusBarRight.Name = "entryStatusBarRight";
		this.entryStatusBarRight.IsEditable = true;
		this.entryStatusBarRight.InvisibleChar = '●';
		this.statusbarMainWindow.Add (this.entryStatusBarRight);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.statusbarMainWindow [this.entryStatusBarRight]));
		w29.Position = 2;
		this.vboxMain.Add (this.statusbarMainWindow);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.statusbarMainWindow]));
		w30.Position = 2;
		w30.Expand = false;
		w30.Fill = false;
		this.Add (this.vboxMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 640;
		this.DefaultHeight = 272;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AboutAction.Activated += new global::System.EventHandler (this.showHelpAboutDialog);
		this.GettingStartedAction.Activated += new global::System.EventHandler (this.gettingStartedDialogShow);
		this.LexiconAction.Activated += new global::System.EventHandler (this.displayLexicon);
		this.WorkTimerAction.Activated += new global::System.EventHandler (this.showWorkTimer);
		this.BreakTimerAction.Activated += new global::System.EventHandler (this.showBreakTimer);
		this.ConfigurationAction.Activated += new global::System.EventHandler (this.showConfigDialog);
		this.LogicalModellerAction.Activated += new global::System.EventHandler (this.showLogicalModeller);
	}
}
