
// This file has been generated by the GUI designer. Do not modify.
namespace workflow
{
	public partial class TimerDialog
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment3;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Entry TimerEntry;
		private global::Gtk.HBox hbox2;
		private global::Gtk.ToggleButton togglebuttonStart;
		private global::Gtk.Button buttonReset;
		private global::Gtk.Label GtkLabel3;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.RadioButton radiobuttonStopwatch;
		private global::Gtk.RadioButton radiobutton2;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.Button buttonSound;
		private global::Gtk.Label GtkLabel6;
		private global::Gtk.Frame frame2;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label1;
		private global::Gtk.Label label2;
		private global::Gtk.Label label3;
		private global::Gtk.HBox hbox4;
		private global::Gtk.HBox hbox5;
		private global::Gtk.SpinButton spinbuttonHours;
		private global::Gtk.Label label4;
		private global::Gtk.HBox hbox6;
		private global::Gtk.SpinButton spinbuttonMinutes;
		private global::Gtk.Label label5;
		private global::Gtk.HBox hbox7;
		private global::Gtk.SpinButton spinbuttonSeconds;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Button buttonSetTimer;
		private global::Gtk.Label GtkLabel8;
		private global::Gtk.Button buttonCancel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget workflow.TimerDialog
			this.Name = "workflow.TimerDialog";
			this.Title = "";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Gravity = ((global::Gdk.Gravity)(9));
			// Internal child workflow.TimerDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.TimerEntry = new global::Gtk.Entry ();
			this.TimerEntry.Name = "TimerEntry";
			this.TimerEntry.IsEditable = false;
			this.TimerEntry.InvisibleChar = '●';
			this.TimerEntry.Xalign = 0.5F;
			this.vbox5.Add (this.TimerEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.TimerEntry]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.togglebuttonStart = new global::Gtk.ToggleButton ();
			this.togglebuttonStart.CanFocus = true;
			this.togglebuttonStart.Name = "togglebuttonStart";
			this.togglebuttonStart.UseUnderline = true;
			this.togglebuttonStart.Label = global::Mono.Unix.Catalog.GetString ("Start");
			this.hbox2.Add (this.togglebuttonStart);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.togglebuttonStart]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonReset = new global::Gtk.Button ();
			this.buttonReset.CanFocus = true;
			this.buttonReset.Name = "buttonReset";
			this.buttonReset.UseUnderline = true;
			this.buttonReset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
			this.hbox2.Add (this.buttonReset);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonReset]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox5.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.GtkAlignment3.Add (this.vbox5);
			this.frame3.Add (this.GtkAlignment3);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Timer:</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel3;
			this.vbox3.Add (this.frame3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.radiobuttonStopwatch = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Stopwatch"));
			this.radiobuttonStopwatch.CanFocus = true;
			this.radiobuttonStopwatch.Name = "radiobuttonStopwatch";
			this.radiobuttonStopwatch.DrawIndicator = true;
			this.radiobuttonStopwatch.UseUnderline = true;
			this.radiobuttonStopwatch.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox2.Add (this.radiobuttonStopwatch);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.radiobuttonStopwatch]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.radiobutton2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Countdown"));
			this.radiobutton2.CanFocus = true;
			this.radiobutton2.Name = "radiobutton2";
			this.radiobutton2.DrawIndicator = true;
			this.radiobutton2.UseUnderline = true;
			this.radiobutton2.Group = this.radiobuttonStopwatch.Group;
			this.vbox2.Add (this.radiobutton2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.radiobutton2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.vbox2.Add (this.alignment2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment2]));
			w11.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.vbox2.Add (this.alignment3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.alignment3]));
			w12.Position = 3;
			// Container child vbox2.Gtk.Box+BoxChild
			this.buttonSound = new global::Gtk.Button ();
			this.buttonSound.CanFocus = true;
			this.buttonSound.Name = "buttonSound";
			this.buttonSound.UseUnderline = true;
			this.buttonSound.Label = global::Mono.Unix.Catalog.GetString ("Sound");
			this.vbox2.Add (this.buttonSound);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.buttonSound]));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			this.GtkAlignment1.Add (this.vbox2);
			this.frame1.Add (this.GtkAlignment1);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Timer Mode Settings:</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel6;
			this.hbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame1]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Hours:");
			this.hbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label1]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Minutes:");
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Seconds:");
			this.hbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label3]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.spinbuttonHours = new global::Gtk.SpinButton (0, 23, 1);
			this.spinbuttonHours.CanFocus = true;
			this.spinbuttonHours.Name = "spinbuttonHours";
			this.spinbuttonHours.Adjustment.PageIncrement = 10;
			this.spinbuttonHours.ClimbRate = 1;
			this.spinbuttonHours.Numeric = true;
			this.hbox5.Add (this.spinbuttonHours);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.spinbuttonHours]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString (":");
			this.hbox5.Add (this.label4);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label4]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.hbox4.Add (this.hbox5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox5]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.spinbuttonMinutes = new global::Gtk.SpinButton (0, 59, 1);
			this.spinbuttonMinutes.CanFocus = true;
			this.spinbuttonMinutes.Name = "spinbuttonMinutes";
			this.spinbuttonMinutes.Adjustment.PageIncrement = 10;
			this.spinbuttonMinutes.ClimbRate = 1;
			this.spinbuttonMinutes.Numeric = true;
			this.spinbuttonMinutes.Value = 20;
			this.hbox6.Add (this.spinbuttonMinutes);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.spinbuttonMinutes]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString (":");
			this.hbox6.Add (this.label5);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label5]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox4.Add (this.hbox6);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox6]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.spinbuttonSeconds = new global::Gtk.SpinButton (0, 59, 1);
			this.spinbuttonSeconds.CanFocus = true;
			this.spinbuttonSeconds.Name = "spinbuttonSeconds";
			this.spinbuttonSeconds.Adjustment.PageIncrement = 10;
			this.spinbuttonSeconds.ClimbRate = 1;
			this.spinbuttonSeconds.Numeric = true;
			this.hbox7.Add (this.spinbuttonSeconds);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.spinbuttonSeconds]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			this.hbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox7]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.vbox4.Add (this.alignment1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.alignment1]));
			w30.Position = 2;
			// Container child vbox4.Gtk.Box+BoxChild
			this.buttonSetTimer = new global::Gtk.Button ();
			this.buttonSetTimer.CanFocus = true;
			this.buttonSetTimer.Name = "buttonSetTimer";
			this.buttonSetTimer.UseUnderline = true;
			this.buttonSetTimer.Label = global::Mono.Unix.Catalog.GetString ("Set Timer");
			this.vbox4.Add (this.buttonSetTimer);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.buttonSetTimer]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			this.GtkAlignment2.Add (this.vbox4);
			this.frame2.Add (this.GtkAlignment2);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Timer Settings:</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel8;
			this.hbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame2]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w35.Position = 1;
			w1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox3]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Internal child workflow.TimerDialog.ActionArea
			global::Gtk.HButtonBox w37 = this.ActionArea;
			w37.Name = "dialog1_ActionArea";
			w37.Spacing = 10;
			w37.BorderWidth = ((uint)(5));
			w37.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w38 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w37 [this.buttonCancel]));
			w38.Expand = false;
			w38.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 383;
			this.DefaultHeight = 269;
			this.Show ();
			this.togglebuttonStart.Toggled += new global::System.EventHandler (this.PauseToggle);
			this.buttonReset.Clicked += new global::System.EventHandler (this.resetTimer);
			this.radiobuttonStopwatch.GroupChanged += new global::System.EventHandler (this.stopwatchSelected);
			this.radiobutton2.GroupChanged += new global::System.EventHandler (this.countdownSelected);
			this.buttonSetTimer.Clicked += new global::System.EventHandler (this.setTimer);
		}
	}
}
