
// This file has been generated by the GUI designer. Do not modify.
namespace workflow
{
	public partial class LexiconDialog
	{
		private global::Gtk.VBox vboxLexiconDialog;
		private global::Gtk.ComboBox comboboxLexiconDialog;
		private global::Gtk.TextView textviewLexiconDialog;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget workflow.LexiconDialog
			this.Name = "workflow.LexiconDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child workflow.LexiconDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vboxLexiconDialog = new global::Gtk.VBox ();
			this.vboxLexiconDialog.Name = "vboxLexiconDialog";
			this.vboxLexiconDialog.Spacing = 6;
			// Container child vboxLexiconDialog.Gtk.Box+BoxChild
			this.comboboxLexiconDialog = global::Gtk.ComboBox.NewText ();
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Accountability:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Activity:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Attribution:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Effectiveness:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Efficiency:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Evaluation:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Expected Result:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Governance:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Government of Canada Outcome:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Horizontal Initiative:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Horizontal Results-Based Management and Accountability Framework (HRMAF):"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Initiative:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Performance criteria:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Input:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Logic Model:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Management Resources and Results Structure (MRRS):"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Outcome:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Immediate Outcome:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Intermediate Outcome:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Final Outcome:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Output:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Performance:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Performance Indicator:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Performance measure:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Performance Measurement:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Performance Monitoring:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Performance Reporting:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Policy:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Plans:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Priorities (for RPP):"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Program:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Program Activity Architecture (PAA):"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Program Activity Architecture, Horizontal:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Reach:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Reports on Plans and Priorities (RPP):"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Result:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Result Chain:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Results-based Management:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Results-based Management and Accountability Framework (RMAF):"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Strategic Outcome:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Target:"));
			this.comboboxLexiconDialog.AppendText (global::Mono.Unix.Catalog.GetString ("Target Group (Target Population):"));
			this.comboboxLexiconDialog.Name = "comboboxLexiconDialog";
			this.comboboxLexiconDialog.Active = 0;
			this.vboxLexiconDialog.Add (this.comboboxLexiconDialog);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxLexiconDialog [this.comboboxLexiconDialog]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vboxLexiconDialog.Gtk.Box+BoxChild
			this.textviewLexiconDialog = new global::Gtk.TextView ();
			this.textviewLexiconDialog.CanFocus = true;
			this.textviewLexiconDialog.Name = "textviewLexiconDialog";
			this.textviewLexiconDialog.Editable = false;
			this.textviewLexiconDialog.CursorVisible = false;
			this.textviewLexiconDialog.AcceptsTab = false;
			this.textviewLexiconDialog.WrapMode = ((global::Gtk.WrapMode)(3));
			this.vboxLexiconDialog.Add (this.textviewLexiconDialog);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxLexiconDialog [this.textviewLexiconDialog]));
			w3.Position = 1;
			w1.Add (this.vboxLexiconDialog);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.vboxLexiconDialog]));
			w4.Position = 0;
			// Internal child workflow.LexiconDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "dialog1_ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.buttonOk]));
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 504;
			this.DefaultHeight = 145;
			this.Show ();
			this.comboboxLexiconDialog.Changed += new global::System.EventHandler (this.LexiconItemSelected);
		}
	}
}
