
// This file has been generated by the GUI designer. Do not modify.
namespace workflow
{
	public partial class PlanningCalendarDialog
	{
		private global::Gtk.HBox hbox4;
		private global::Gtk.Calendar calendarProject;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label label8;
		private global::Gtk.ComboBoxEntry comboboxentryProjectDates;
		private global::Gtk.Button button599;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.Button button600;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget workflow.PlanningCalendarDialog
			this.Name = "workflow.PlanningCalendarDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Project Planning Calendar Date Entry");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child workflow.PlanningCalendarDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.calendarProject = new global::Gtk.Calendar ();
			this.calendarProject.CanFocus = true;
			this.calendarProject.Name = "calendarProject";
			this.calendarProject.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox4.Add (this.calendarProject);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.calendarProject]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Select or edit new project event:");
			this.vbox6.Add (this.label8);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label8]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.comboboxentryProjectDates = global::Gtk.ComboBoxEntry.NewText ();
			this.comboboxentryProjectDates.AppendText (global::Mono.Unix.Catalog.GetString ("Project start date."));
			this.comboboxentryProjectDates.AppendText (global::Mono.Unix.Catalog.GetString ("Project end date."));
			this.comboboxentryProjectDates.Name = "comboboxentryProjectDates";
			this.vbox6.Add (this.comboboxentryProjectDates);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.comboboxentryProjectDates]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.button599 = new global::Gtk.Button ();
			this.button599.CanFocus = true;
			this.button599.Name = "button599";
			this.button599.UseUnderline = true;
			this.button599.Label = global::Mono.Unix.Catalog.GetString ("Enter project date.");
			this.vbox6.Add (this.button599);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button599]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.vbox6.Add (this.alignment2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.alignment2]));
			w6.Position = 3;
			// Container child vbox6.Gtk.Box+BoxChild
			this.button600 = new global::Gtk.Button ();
			this.button600.CanFocus = true;
			this.button600.Name = "button600";
			this.button600.UseUnderline = true;
			this.button600.Label = global::Mono.Unix.Catalog.GetString ("Today");
			this.vbox6.Add (this.button600);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.button600]));
			w7.Position = 4;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox4.Add (this.vbox6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox6]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			w1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox4]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Internal child workflow.PlanningCalendarDialog.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog1_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.buttonCancel]));
			w11.Expand = false;
			w11.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.buttonOk]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 425;
			this.DefaultHeight = 218;
			this.Show ();
		}
	}
}
